image: ubuntu:latest
stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - mv index.html ./public
    - mv vendors ./public
    - mv resources ./public
  artifacts:
    paths:
      - public